typography_spectrum: 0.02895607602404486
color:
  brandStrength: 0.3170648624580169
  lightness: 0.33659081633755994
  saturation: 0.019542109428600657
  rhythmicContrast: 0.3330945077916552
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
github: true
layout_spectrum: 0.6931683418996595
analytics:
  twitter: Private
author:
  name: Steve GW
  email: stevegwusa@gmail.com
name: 'Art Show July-26th-Aug-4th '
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Where
    id: 73d27468-f9fb-4ac7-b805-d12cf0cfae6b
    type: content
  - name: 'Location '
    id: d7e6a7ce-3d9b-431a-aa4a-f549de02fa9f
    type: content
  - name: Home
    url: 'https://thegrid.ai/augustshow'
    type: external
title: Expressions Artist Show
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/9552fd77-0ca7-47e2-bc26-3555ec0743c1.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/9552fd77-0ca7-47e2-bc26-3555ec0743c1.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/4a043a47-426e-4a21-861f-c6f1c388f723.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/4a043a47-426e-4a21-861f-c6f1c388f723.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
coverPrefs:
  filter: false
description: '* Artists and their joy of Art'
purpose:
  - type: contact
    url: 'mailto:cmtorrez76@yahoo.com'
    label: Christine Torrez
